import process from 'node:process'
import { migrate as migratePg } from 'drizzle-orm/node-postgres/migrator'
import { db, pool } from '../postgre-sql'
import { ensurePostgresDatabase } from './ensure-postgres-db'
import { hasPostgresSchemaTables } from './has-postgres-schema-tables'

/**
 * 已有核心表时补建 genealogy（跳过全量 0000 迁移时仍需增量建表）。
 */
async function ensureGenealogyTable() {
    await pool.query(`
        CREATE TABLE IF NOT EXISTS "genealogy" (
            "id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
            "name" text NOT NULL,
            "parent" integer NOT NULL,
            "sex" text,
            "desc" text,
            "parent_name" text
        )
    `)
    console.log('[postgres] ensured genealogy table.')
}

(async () => {
    try {
        await ensurePostgresDatabase()

        if (await hasPostgresSchemaTables(pool)) {
            console.log('[postgres] schema tables already exist, skipping baseline migrations.')
            await ensureGenealogyTable()
            return
        }

        await migratePg(db, { migrationsFolder: './drizzle-postgre' })
        console.log('PostgreSQL migrations applied.')
    }
    catch (err) {
        console.error('PostgreSQL migration failed:', err)
        process.exit(1)
    }
    finally {
        await pool.end()
    }
})()
