/* eslint-disable node/prefer-global/process */
import { Database } from 'bun:sqlite'
import { drizzle as drizzleSqlite } from 'drizzle-orm/bun-sqlite'

import { config } from '~/config'
import { pool } from '~/db/postgre-sql'
import * as sqliteSchema from '~/db/schema/sqlite'
import { ensurePostgresDatabase } from '~/db/utils/ensure-postgres-db'

/**
 * 确保 PostgreSQL 中存在 genealogy 表。
 */
async function ensureGenealogyTable() {
    await pool.query(`
        CREATE TABLE IF NOT EXISTS "genealogy" (
            "id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
            "name" text NOT NULL,
            "parent" integer NOT NULL,
            "sex" text,
            "desc" text,
            "parent_name" text
        )
    `)
}

/**
 * 将本地 SQLite 中的 genealogy 数据幂等同步到 PostgreSQL（按 id upsert）。
 */
async function migrateGenealogyToPostgres() {
    await ensurePostgresDatabase()
    await ensureGenealogyTable()

    const sqlite = new Database(config.db.sqlite)
    const sqliteDb = drizzleSqlite({ client: sqlite, schema: sqliteSchema })
    const rows = await sqliteDb.select().from(sqliteSchema.genealogy)

    console.log(`[genealogy] SQLite 记录数: ${rows.length}`)

    let upserted = 0
    for (const row of rows) {
        await pool.query(
            `INSERT INTO genealogy (id, name, parent, sex, "desc", parent_name)
             VALUES ($1, $2, $3, $4, $5, $6)
             ON CONFLICT (id) DO UPDATE SET
               name = EXCLUDED.name,
               parent = EXCLUDED.parent,
               sex = EXCLUDED.sex,
               "desc" = EXCLUDED."desc",
               parent_name = EXCLUDED.parent_name`,
            [row.id, row.name, row.parent, row.sex, row.desc, row.parent_name],
        )
        upserted += 1
    }

    // 同步序列，避免后续自增冲突
    await pool.query(`
        SELECT setval(
            pg_get_serial_sequence('genealogy', 'id'),
            COALESCE((SELECT MAX(id) FROM genealogy), 1),
            true
        )
    `)

    console.log(`[genealogy] 已同步到 PostgreSQL: ${upserted} 条`)
    sqlite.close()
}

(async () => {
    try {
        await migrateGenealogyToPostgres()
    }
    catch (err) {
        console.error('族谱数据迁移到 PostgreSQL 失败:', err)
        process.exit(1)
    }
    finally {
        await pool.end()
    }
})()
