CREATE TABLE IF NOT EXISTS "genealogy" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "genealogy_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"name" text NOT NULL,
	"parent" integer NOT NULL,
	"sex" text,
	"desc" text,
	"parent_name" text
);
